OLLAMA_BASE_URL = "http://localhost:11434"

OLLAMA_CHAT_URL = f"{OLLAMA_BASE_URL}/api/chat"

OLLAMA_MODEL = "llama3.1:8b"

OLLAMA_TIMEOUT = 120

MAX_CONVERSATION_TURNS = 6

MIN_CONVERSATION_TURNS_FOR_REPORT = 3
